---
version: 2.1

references:
  job_defaults: &job_defaults
    docker:
      - image: circleci/node:14-browsers
    environment:
      - TERM: xterm
      - BUILD_TARGET: ./dist

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restoring node_modules and yarn cache
      keys:
        - yarn-v1-{{ checksum ".nvmrc" }}-{{ checksum "package-lock.json" }}
        - yarn-v1-{{ checksum ".nvmrc" }}

  install_deps: &install_deps
    run:
      name: Install Dependencies
      command: npm install
      environment:
        NODE_ENV: development

  cache_node_modules: &cache_node_modules
    save_cache:
      name: Caching node_modules
      key: yarn-v1-{{ checksum ".nvmrc" }}-{{ checksum "package-lock.json" }}
      paths:
        - node_modules

jobs:
  deps:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_node_modules
      - *install_deps
      - *cache_node_modules

  lint:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_node_modules
      - run: npm run lint

  build:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_node_modules
      - run: npm run build
      - persist_to_workspace:
          root: ~/project
          paths: .

  # NPM_TOKEN is a automatable publish token, assigned to the gocardless npm
  # organisation. This step publishes the files that were build in build.
  publish:
    <<: *job_defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish --access=public

workflows:
  version: 2
  build:
    jobs:
      - deps:
          filters:
            tags:
              only: /^v.*/
      - lint:
          requires:
            - deps
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - deps
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - lint
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
